### ISSUE TITLE
Non void function does not return anything

### ISSUE THREAD

**Issue by xylafur** [techmexdev/CS-APP3e#1]
Your main function in `hello.c` should be returning an int, but instead it returns nothing

```
#include <stdio.h>

int main() {
  printf("hello, world\n");
}
```
It is generally best practice to have functions return the correct type

**Comment by techmexdev** [comment]
orale! thanks!

**Comment by techmexdev** [comment]
fixed with this commit https://github.com/techmexdev/CS-APP3e/commit/10cdd2a0054cb8c86cc15802a5ca5d9b8590548d @xylafur
